# Generated by Django 4.1.3 on 2022-11-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointment",
            "0002_remove_patient_insurance_id_confirmation_conf_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="confirmation",
            name="time",
            field=models.IntegerField(default=6),
        ),
    ]
