# Generated by Django 4.1.3 on 2022-11-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0003_confirmation_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="patient_id",
            field=models.IntegerField(default=4),
        ),
    ]
