# Generated by Django 4.1.3 on 2022-11-16 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0004_patient_patient_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="confirmation", name="conf_number",),
        migrations.RemoveField(model_name="confirmation", name="time",),
        migrations.RemoveField(model_name="patient", name="patient_age",),
        migrations.RemoveField(model_name="patient", name="patient_id",),
    ]
