# Generated by Django 4.1.3 on 2022-11-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0005_remove_confirmation_conf_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="confirmation",
            name="conf_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="confirmation",
            name="time",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="doctor", name="doctor_id", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="patient",
            name="patient_age",
            field=models.IntegerField(default=0),
        ),
    ]
