# Generated by Django 4.1.3 on 2022-11-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0006_confirmation_conf_number_confirmation_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="patient_id",
            field=models.IntegerField(default=0),
        ),
    ]
